In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.set_option('display.max_columns', None) # display all the columns of a dataframe
pd.set_option('display.max_rows', 100)

### Extracting Income from census

In [5]:
education = pd.read_csv('../../education/ACSST1Y2019.S1501_data_with_overlays_2020-12-09T112526.csv')

In [6]:
#Income related all earnings columns by education
financial_education_full=education[['NAME','S1501_C03_059E','S1501_C03_060E', 'S1501_C03_061E','S1501_C03_062E',\
'S1501_C03_063E', 'S1501_C03_064E']]

In [7]:
#Income related all earnings columns by education
financial_education_full.columns = ['county','median_earnings', 'less_than_highschool','highschool','associate','bachelors','graduate']

In [8]:
#Income related all earnings columns by education
#Income related all earnings columns by education
financial_education_full=financial_education_full.drop(financial_education_full.index[0])
#Income related all earnings columns by education
financial_education_full

,county,median_earnings,less_than_highschool,highschool,associate,bachelors,graduate
1,"Atlantic County, New Jersey",45935,30979,40842,40636,65149,91550
2,"Bergen County, New Jersey",72267,31753,46527,60363,90190,121168
3,"Burlington County, New Jersey",61748,28479,46742,54086,81334,101081
4,"Camden County, New Jersey",51486,30276,40350,46672,68808,103320
5,"Cape May County, New Jersey",51483,45524,40796,55689,75087,107240
6,"Cumberland County, New Jersey",34905,25125,27968,50911,71310,130111
7,"Essex County, New Jersey",51029,31652,36421,50611,78232,120471
8,"Gloucester County, New Jersey",64004,38567,50299,62409,75764,102354
9,"Hudson County, New Jersey",58372,35137,36257,47780,76719,109624
10,"Hunterdon County, New Jersey",80882,30165,51430,52398,110452,137816
11,"Mercer County, New Jersey",57023,32171,35360,43924,80437,106547
12,"Middlesex County, New Jersey",65047,36941,42205,53050,80361,112777
13,"Monmouth County, New Jersey",76140,31428,53153,62434,86660,125783
14,"Morris County, New Jersey",81064,31908,50543,61793,100456,130293
15,"Ocean County, New Jersey",60454,38789,50205,58046,72213,91473
16,"Passaic County, New Jersey",48493,32002,38572,50369,72782,96093
17,"Salem County, New Jersey",57340,27204,36939,68689,76042,108496
18,"Somerset County, New Jersey",81377,27204,51048,71296,88698,122406
19,"Sussex County, New Jersey",68713,45429,51576,62094,90023,104967
20,"Union County, New Jersey",52001,31983,41917,51647,63375,119002
21,"Warren County, New Jersey",67667,56455,46926,61519,84795,111194

In [9]:
#Income related all earnings columns by education
financial_education_full.to_csv('financial_education.csv')

In [10]:
financial_education_acolumn = education[['NAME','S1501_C03_059E']]
financial_education_acolumn.columns = ['county','median_earnings']

In [11]:
financial_education_acolumn=financial_education_acolumn.drop(financial_education_acolumn.index[0])
financial_education_acolumn

                           county median_earnings
1     Atlantic County, New Jersey           45935
2       Bergen County, New Jersey           72267
3   Burlington County, New Jersey           61748
4       Camden County, New Jersey           51486
5     Cape May County, New Jersey           51483
6   Cumberland County, New Jersey           34905
7        Essex County, New Jersey           51029
8   Gloucester County, New Jersey           64004
9       Hudson County, New Jersey           58372
10   Hunterdon County, New Jersey           80882
11      Mercer County, New Jersey           57023
12   Middlesex County, New Jersey           65047
13    Monmouth County, New Jersey           76140
14      Morris County, New Jersey           81064
15       Ocean County, New Jersey           60454
16     Passaic County, New Jersey           48493
17       Salem County, New Jersey           57340
18    Somerset County, New Jersey           81377
19      Sussex County, New Jersey           68713
20       Union County, New Jersey           52001
21      Warren County, New Jersey           67667

In [12]:
financial_education_acolumn['median_earnings'] = financial_education_acolumn['median_earnings'].astype(int)
financial_education_acolumn.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21 entries, 1 to 21
Data columns (total 2 columns):
county             21 non-null object
median_earnings    21 non-null int64
dtypes: int64(1), object(1)
memory usage: 504.0+ bytes

In [13]:
financial_education_acolumn.to_csv('median_earnings.csv')

### Extracting Education

In [28]:
education_age=education[['NAME','S1501_C04_002E', 'S1501_C04_003E', 'S1501_C04_004E', 'S1501_C04_005E', \
                         'S1501_C04_007E','S1501_C04_008E', 'S1501_C04_009E', 'S1501_C04_010E', 'S1501_C04_011E', \
                         'S1501_C04_012E', 'S1501_C04_013E', 'S1501_C04_014E', 'S1501_C04_015E', 'S1501_C04_017E', \
                         'S1501_C04_018E', 'S1501_C04_020E', 'S1501_C04_021E', 'S1501_C04_023E', 'S1501_C04_024E', \
                         'S1501_C04_026E','S1501_C04_027E']]

In [29]:
education_age.columns =['county','18_24_less_than_HS',
       '18_24_HS_grad',
       "18_24_associate",
       "18_24_bachelor",
       'over_25_less_9grade',
       'over_25_9_12th grade_no_diploma',
       'over_25_HS_grad',
       'over_25_some_college_no_degree',
       "over_25_associate",
       "over_25_bachelors",
       'over_25_graduate',
       'over_25_HS_grad_or_higher',
       "over_25_bachelors_or_higher",
       '25_34_HS_grad_or_higher',
       "25_34_bachelors_or_higher",
       '35_44_HS_grad_or_higher',
       "35_44_bachelors_or_higher",
       '45_64_HS_grad_or_higher',
       "45_64_bachelors_or_higher",
       'over_65_HS_grad_or_higher',
       "over_65_bachelors_or_higher"]

In [30]:
education_age=education_age.drop(education_age.index[0])

In [31]:
# education_metadata = pd.read_csv('./education/ACSST1Y2019.S1501_metadata_2020-12-09T112526.csv')
#education_metadata.id.unique()

In [32]:
education_age_real_nums = education[['NAME', 'S1501_C01_001E', \
'S1501_C01_002E', 'S1501_C01_003E', 'S1501_C01_004E', 'S1501_C01_005E', 'S1501_C01_006E', 'S1501_C01_007E', 'S1501_C01_008E', \
'S1501_C01_009E', 'S1501_C01_010E', 'S1501_C01_011E', 'S1501_C01_012E', 'S1501_C01_013E', 'S1501_C01_014E', 'S1501_C01_015E', \
'S1501_C01_016E', 'S1501_C01_017E', \
'S1501_C01_018E', 'S1501_C01_019E', 'S1501_C01_020E', 'S1501_C01_021E', 'S1501_C01_022E', 'S1501_C01_023E', 'S1501_C01_024E', 
'S1501_C01_025E', 'S1501_C01_026E', 'S1501_C01_027E']]

In [33]:
education_age_real_nums.columns = ['county',
       'Pop18_24',
'18_24_less_than_HS',
'18_24_HS_grad',
"18_24_associate",
        "18_24_bachelor",   
       'Pop_over_25',
       'over_25_less_9grade',
       'over_25_9_12th grade_no_diploma',
       'over_25_HS_grad',
       'over_25_some_college_no_degree',
       "over_25_associate",
       "over_25_bachelors",
       'over_25_graduate',
       'over_25_HS_grad_or_higher',
       'over_25_bachelors_or_higher',
       'Pop25_34',
       '25_34_HS_grad_or_higher',
       "25_34_bachelors_or_higher",
       'Pop35_44',
       '35_44_HS_grad_or_higher',      
       "35_44_bachelors_or_higher",
       'Pop45_64',
       '45_64_HS_grad_or_higher',
       "45_64_bachelors_or_higher",
       'Pop_over_65',
       'over_65_HS_grad_or_higher',
       "over_65_bachelors_or_higher"]

In [34]:
education_age_real_nums=education_age_real_nums.drop(education_age_real_nums.index[0])
#education_age_real_nums['18_24_less_than_HS'].astype(int)

In [35]:
education_age_real_nums['Pop18_24']=education_age_real_nums['Pop18_24'].astype(int)
education_age_real_nums['18_24_less_than_HS']=education_age_real_nums['18_24_less_than_HS'].astype(int)
education_age_real_nums['18_24_HS_grad']=education_age_real_nums['18_24_HS_grad'].astype(int)
education_age_real_nums["18_24_associate"]=education_age_real_nums["18_24_associate"].astype(int)
education_age_real_nums["18_24_bachelor"]=education_age_real_nums["18_24_bachelor"].astype(int)
education_age_real_nums['Pop_over_25']=education_age_real_nums['Pop_over_25'].astype(int)
education_age_real_nums['over_25_less_9grade']=education_age_real_nums['over_25_less_9grade'].astype(int)
education_age_real_nums['over_25_9_12th grade_no_diploma']=education_age_real_nums['over_25_9_12th grade_no_diploma'].astype(int)
education_age_real_nums['over_25_HS_grad']=education_age_real_nums['over_25_HS_grad'].astype(int)
education_age_real_nums['over_25_some_college_no_degree']=education_age_real_nums['over_25_some_college_no_degree'].astype(int)
education_age_real_nums["over_25_associate"]=education_age_real_nums["over_25_associate"].astype(int)
education_age_real_nums["over_25_bachelors"]=education_age_real_nums["over_25_bachelors"].astype(int)
education_age_real_nums['over_25_graduate']=education_age_real_nums['over_25_graduate'].astype(int)
education_age_real_nums['over_25_HS_grad_or_higher']=education_age_real_nums['over_25_HS_grad_or_higher'].astype(int)
education_age_real_nums['over_25_bachelors_or_higher']=education_age_real_nums['over_25_bachelors_or_higher'].astype(int)
education_age_real_nums['Pop25_34']=education_age_real_nums['Pop25_34'].astype(int)
education_age_real_nums['25_34_HS_grad_or_higher']=education_age_real_nums['25_34_HS_grad_or_higher'].astype(int)
education_age_real_nums["25_34_bachelors_or_higher"]=education_age_real_nums["25_34_bachelors_or_higher"].astype(int)
education_age_real_nums['Pop35_44']=education_age_real_nums['Pop35_44'].astype(int)
education_age_real_nums['35_44_HS_grad_or_higher']= education_age_real_nums['35_44_HS_grad_or_higher'].astype(int)     
education_age_real_nums["35_44_bachelors_or_higher"]=education_age_real_nums["35_44_bachelors_or_higher"].astype(int)
education_age_real_nums['Pop45_64']=education_age_real_nums['Pop45_64'].astype(int)
education_age_real_nums['45_64_HS_grad_or_higher']=education_age_real_nums['45_64_HS_grad_or_higher'].astype(int)
education_age_real_nums["45_64_bachelors_or_higher"]=education_age_real_nums["45_64_bachelors_or_higher"].astype(int)
education_age_real_nums['Pop_over_65']=education_age_real_nums['Pop_over_65'].astype(int)
education_age_real_nums['over_65_HS_grad_or_higher']=education_age_real_nums['over_65_HS_grad_or_higher'].astype(int)
education_age_real_nums["over_65_bachelors_or_higher"]=education_age_real_nums["over_65_bachelors_or_higher"].astype(int)

In [36]:
# education_age_real_nums['Pop18_24','18_24_less_than_HS','18_24_HS_grad',"18_24_associate","18_24_bachelor",\
#                          'Pop_over_25','over_25_less_9grade','over_25_9_12th grade_no_diploma','over_25_HS_grad',\
#                          'over_25_some_college_no_degree',"over_25_associate", "over_25_bachelors",'over_25_graduate',\
#                          'over_25_HS_grad_or_higher','over_25_bachelors_or_higher','Pop25_34',\
#                          '25_34_HS_grad_or_higher',"25_34_bachelors_or_higher",'Pop35_44','35_44_HS_grad_or_higher',\
#                          "35_44_bachelors_or_higher", 'Pop45_64','45_64_HS_grad_or_higher',"45_64_bachelors_or_higher",\
#                          'Pop_over_65','over_65_HS_grad_or_higher',"over_65_bachelors_or_higher"] = \
# education_age_real_nums['Pop18_24','18_24_less_than_HS','18_24_HS_grad',"18_24_associate","18_24_bachelor",\
#                          'Pop_over_25','over_25_less_9grade','over_25_9_12th grade_no_diploma','over_25_HS_grad',\
#                          'over_25_some_college_no_degree',"over_25_associate", "over_25_bachelors",'over_25_graduate',\
#                          'over_25_HS_grad_or_higher','over_25_bachelors_or_higher','Pop25_34',\
#                          '25_34_HS_grad_or_higher',"25_34_bachelors_or_higher",'Pop35_44','35_44_HS_grad_or_higher',\
#                          "35_44_bachelors_or_higher", 'Pop45_64','45_64_HS_grad_or_higher',"45_64_bachelors_or_higher",\
#                          'Pop_over_65','over_65_HS_grad_or_higher',"over_65_bachelors_or_higher"].apply(pd.to_numeric, errors='coerce', axis=1)

In [37]:
#Adding for 18-24 age bracket
education_age_real_nums['18_24_less_HS_HSgrad'] = education_age_real_nums['18_24_less_than_HS']+education_age_real_nums['18_24_HS_grad']
education_age_real_nums['18_24_associate_bachelor']=education_age_real_nums['18_24_associate']+education_age_real_nums['18_24_bachelor']

#Adding for over 25 age bracket
education_age_real_nums['over_25_less_than_HS']=education_age_real_nums['over_25_less_9grade'] +education_age_real_nums['over_25_9_12th grade_no_diploma']

#Adding Pop25_34	Pop35_44	Pop45_64	Pop_over_65 to extract percentages
education_age_real_nums['Pop_over25'] =  education_age_real_nums['Pop25_34']+education_age_real_nums['Pop35_44']+\
education_age_real_nums['Pop45_64']+education_age_real_nums['Pop_over_65']

In [38]:
education_age_real_nums=education_age_real_nums.drop(['45_64_HS_grad_or_higher','over_65_HS_grad_or_higher','35_44_HS_grad_or_higher','25_34_HS_grad_or_higher',\
                             "45_64_bachelors_or_higher","over_65_bachelors_or_higher","35_44_bachelors_or_higher",\
                              "25_34_bachelors_or_higher",'over_25_HS_grad', 'over_25_some_college_no_degree', 'over_25_associate',\
                              'over_25_bachelors', 'over_25_graduate','18_24_less_than_HS', '18_24_HS_grad',\
                              '18_24_associate', '18_24_bachelor','Pop_over_25', 'over_25_less_9grade',\
                              'over_25_9_12th grade_no_diploma','Pop25_34','Pop35_44','Pop45_64','Pop_over_65',\
                                                     'over_25_bachelors_or_higher'],axis=1)

#The columns below sum up to over_25_HS_grad_or_higher (160,782 for Atlantic city)
#education_age_real_nums.drop(['over_25_HS_grad', 'over_25_some_college_no_degree', 'over_25_associate', 'over_25_bachelors', 'over_25_graduate'], axis=1)
#Pop18_24, Pop_over_25,'Pop25_34','Pop35_44','Pop45_64','Pop_over_65'


#The columns below were aggregated into two columns - ['18-24_less_than_HS_HSgrad'] and ['18_24_associate_bachelor'] 
#- and were dropped
#18_24_less_than_HS	18_24_HS_grad	18_24_associate	18_24_bachelor

#The columns below were aggregated into -['over_25_less_than_HS']- and were dropped
#Pop_over_25	over_25_less_9grade	over_25_9_12th grade_no_diploma

In [39]:
education_age_real_nums

,county,Pop18_24,over_25_HS_grad_or_higher,18_24_less_HS_HSgrad,18_24_associate_bachelor,over_25_less_than_HS,Pop_over25
1,"Atlantic County, New Jersey",24683,160782,9754,14929,22710,183492
2,"Bergen County, New Jersey",74163,614966,23791,50372,46763,661729
3,"Burlington County, New Jersey",36899,297585,16483,20416,18706,316291
4,"Camden County, New Jersey",41040,315138,18797,22243,36288,351426
5,"Cape May County, New Jersey",6132,65427,3399,2733,4530,69957
6,"Cumberland County, New Jersey",11270,83405,6306,4964,19296,102701
7,"Essex County, New Jersey",69333,469019,32059,37274,71245,540264
8,"Gloucester County, New Jersey",25981,188357,8571,17410,14199,202556
9,"Hudson County, New Jersey",52068,414752,18414,33654,69044,483796
10,"Hunterdon County, New Jersey",9882,85578,4480,5402,5199,90777
11,"Mercer County, New Jersey",41153,220328,13037,28116,27887,248215
12,"Middlesex County, New Jersey",76973,506264,26503,50470,63377,569641
13,"Monmouth County, New Jersey",49925,416223,17222,32703,23044,439267
14,"Morris County, New Jersey",41892,329541,15156,26736,17933,347474
15,"Ocean County, New Jersey",43993,387077,16012,27981,29426,416503
16,"Passaic County, New Jersey",48205,285611,26053,22152,48992,334603
17,"Salem County, New Jersey",5015,38801,1626,3389,5440,44241
18,"Somerset County, New Jersey",27734,217673,9386,18348,12770,230443
19,"Sussex County, New Jersey",11404,96107,4783,6621,5731,101838
20,"Union County, New Jersey",46439,327864,17470,28969,51989,379853
21,"Warren County, New Jersey",8753,71112,3013,5740,5050,76162

# This one is too look at!!!

### Education - two columns - "less than High School" and "more than High School"

In [92]:
education_nums_percentage = education_age_real_nums.copy()
education_nums_percentage['Hs_and_less']=education_nums_percentage['over_25_less_than_HS']+education_nums_percentage['18_24_less_HS_HSgrad']
education_nums_percentage['Hs_and_more']=education_nums_percentage['18_24_associate_bachelor'] + education_nums_percentage['over_25_HS_grad_or_higher']
education_nums_percentage['Population'] = education_nums_percentage['Pop18_24'] + education_nums_percentage['Pop_over25']
education_nums_percentage['%Hs_and_less'] = (education_nums_percentage['Hs_and_less']/education_nums_percentage['Population']*100).round(1)
education_nums_percentage['%Hs_and_more'] = (education_nums_percentage['Hs_and_more']/education_nums_percentage['Population']*100).round(1)

In [93]:
education_nums_percentage=education_nums_percentage.drop(['over_25_HS_grad_or_higher','18_24_less_HS_HSgrad','18_24_associate_bachelor',\
                                'over_25_less_than_HS','Pop_over25','Pop18_24','Pop_over25','Population'], axis=1)
education_nums_percentage.columns = ['county', 'HS_and_less', 'HS_and_more','%HS_and_less', '%HS_and_more']

In [94]:
education_nums_percentage

,county,HS_and_less,HS_and_more,%HS_and_less,%HS_and_more
1,"Atlantic County, New Jersey",32464,175711,15.6,84.4
2,"Bergen County, New Jersey",70554,665338,9.6,90.4
3,"Burlington County, New Jersey",35189,318001,10.0,90.0
4,"Camden County, New Jersey",55085,337381,14.0,86.0
5,"Cape May County, New Jersey",7929,68160,10.4,89.6
6,"Cumberland County, New Jersey",25602,88369,22.5,77.5
7,"Essex County, New Jersey",103304,506293,16.9,83.1
8,"Gloucester County, New Jersey",22770,205767,10.0,90.0
9,"Hudson County, New Jersey",87458,448406,16.3,83.7
10,"Hunterdon County, New Jersey",9679,90980,9.6,90.4
11,"Mercer County, New Jersey",40924,248444,14.1,85.9
12,"Middlesex County, New Jersey",89880,556734,13.9,86.1
13,"Monmouth County, New Jersey",40266,448926,8.2,91.8
14,"Morris County, New Jersey",33089,356277,8.5,91.5
15,"Ocean County, New Jersey",45438,415058,9.9,90.1
16,"Passaic County, New Jersey",75045,307763,19.6,80.4
17,"Salem County, New Jersey",7066,42190,14.3,85.7
18,"Somerset County, New Jersey",22156,236021,8.6,91.4
19,"Sussex County, New Jersey",10514,102728,9.3,90.7
20,"Union County, New Jersey",69459,356833,16.3,83.7
21,"Warren County, New Jersey",8063,76852,9.5,90.5

In [95]:
education_nums_percentage.to_csv('education_num_percentage.csv')

### Education in percentage (all population columns dropped)

In [84]:
education_percent=education_age_real_nums.copy()

In [86]:
education_percent['18_24_less_HS_HSgrad%']=(education_percent['18_24_less_HS_HSgrad']/education_percent['Pop18_24']*100).round(1)
education_percent['18_24_associate_bachelor%']=(education_percent['18_24_associate_bachelor']/education_percent['Pop18_24']*100).round(1)
education_percent['over_25_less_than_HS%']=(education_percent['over_25_less_than_HS']/education_percent['Pop_over25']*100).round(1)
education_percent['over_25_HS_grad_or_higher%']=(education_percent['over_25_HS_grad_or_higher']/education_percent['Pop_over25']*100).round(1)
education_percent['over_25_bachelors_or_higher%']=(education_percent['over_25_bachelors_or_higher']/education_percent['Pop_over25']*100).round(1)

In [89]:
education_percent=education_percent.drop(['Pop18_24', 'over_25_HS_grad_or_higher', 'over_25_bachelors_or_higher', '18_24_less_HS_HSgrad',\
                        '18_24_associate_bachelor', 'over_25_less_than_HS', 'Pop_over25'], axis=1)

In [90]:
education_percent

,county,18_24_less_HS_HSgrad%,18_24_associate_bachelor%,over_25_less_than_HS%,over_25_HS_grad_or_higher%,over_25_bachelors_or_higher%
1,"Atlantic County, New Jersey",39.5,60.5,12.4,87.6,28.2
2,"Bergen County, New Jersey",32.1,67.9,7.1,92.9,52.0
3,"Burlington County, New Jersey",44.7,55.3,5.9,94.1,39.5
4,"Camden County, New Jersey",45.8,54.2,10.3,89.7,33.6
5,"Cape May County, New Jersey",55.4,44.6,6.5,93.5,32.1
6,"Cumberland County, New Jersey",56.0,44.0,18.8,81.2,16.1
7,"Essex County, New Jersey",46.2,53.8,13.2,86.8,35.7
8,"Gloucester County, New Jersey",33.0,67.0,7.0,93.0,34.0
9,"Hudson County, New Jersey",35.4,64.6,14.3,85.7,45.2
10,"Hunterdon County, New Jersey",45.3,54.7,5.7,94.3,54.1
11,"Mercer County, New Jersey",31.7,68.3,11.2,88.8,44.5
12,"Middlesex County, New Jersey",34.4,65.6,11.1,88.9,43.8
13,"Monmouth County, New Jersey",34.5,65.5,5.2,94.8,48.2
14,"Morris County, New Jersey",36.2,63.8,5.2,94.8,56.5
15,"Ocean County, New Jersey",36.4,63.6,7.1,92.9,32.3
16,"Passaic County, New Jersey",54.0,46.0,14.6,85.4,29.1
17,"Salem County, New Jersey",32.4,67.6,12.3,87.7,20.0
18,"Somerset County, New Jersey",33.8,66.2,5.5,94.5,56.0
19,"Sussex County, New Jersey",41.9,58.1,5.6,94.4,38.1
20,"Union County, New Jersey",37.6,62.4,13.7,86.3,37.2
21,"Warren County, New Jersey",34.4,65.6,6.6,93.4,33.9

In [91]:
education_percent.to_csv('education_percent.csv')

### Age

In [ ]:
age = education[['NAME', 'S1501_C01_001E','S1501_C01_006E','S1501_C01_016E', 'S1501_C01_022E',\
'S1501_C01_025E']]

In [ ]:
age.columns = ['name','18_24_years','over_25','25_34_years','45_64_years','over_65']

In [ ]:
age=age.drop(age.index[0])

In [ ]:
age

In [ ]:
age.to_csv('age.csv')